# Generated by Django 2.0 on 2017-12-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
