# Generated by Django 2.0 on 2018-01-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_auto_20180101_1229'),
        ('Account', '0004_auto_20171230_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_albums',
            field=models.ManyToManyField(blank=True, to='Music.Album'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
