# Generated by Django 2.0 on 2018-01-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20180101_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
