# Generated by Django 2.0 on 2017-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20171217_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='related_genres',
            field=models.ForeignKey(null=True, on_delete=models.SET('None'), to='Music.Genre'),
        ),
    ]
