# Generated by Django 2.0 on 2017-12-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_album_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.Genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='realeased',
            field=models.DateField(null=True),
        ),
    ]
