# Generated by Django 2.0 on 2018-01-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_auto_20171219_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(null=True, upload_to='albums'),
        ),
    ]
